### ISSUE TITLE
Improve the documentation.

### ISSUE THREAD

**Issue by SCHW18TZ** [SCHW18TZ/Snippets4Dummies#5]
I need someone to go through the snippet code and update the README.md file with the documentation accordingly. Please reach out to me if anyone wants to be assigned to this issue

**Comment by vikash485** [comment]
Hey @SCHW18TZ, I can't understand the issue properly, can you please explain what does someone have to do in this?

**Comment by SCHW18TZ** [comment]
Hey @vikash485, As you can see in the snippets folder, there are a lot more commands then just `!elnav`. I need someone to write the documentation for other commands as well. Do let me know if you are comfortable with this issue. I'll assign this to you!

**Comment by vikash485** [comment]
Thanks a lot for that, I would like to contribute for this issue, please assign it to me.
