### ISSUE TITLE
contributing.md file missing 

### ISSUE THREAD

**Issue by nileshlad09** [SCHW18TZ/Snippets4Dummies#6]
According to hacktoberfest guidelines a contributing.md file should be there for projects which are participating in hacktoberfest.
Please assign this issue to me...

**Comment by SCHW18TZ** [comment]
Okay, I have assigned it to you, Good Luck!

**Comment by nileshlad09** [comment]
can you please add tag of hactoberfest

**Comment by SCHW18TZ** [comment]
They are added to the main repo so no need to add them here but I guess I'll add it regardless.
